done BUZ-131, add tests, add experimental Proxy validation
buzzi-io/buzzi-sdk-node pull request #1
Opened 2017-05-08 14:40 UTC by tttmaximttt

2017-05-08 16:02 UTC, DerekSeverson requested changes
See inline comments.

2017-05-08 16:02 UTC, DerekSeverson commented on .gitignore
> +.idea/workspace.xml
@tttmaximttt just gitignore `.idea` which will ignore the entire folder and everything inside.

2017-05-08 16:02 UTC, DerekSeverson commented on lib/service.js
> +    return proxy;
@tttmaximttt - I would remove the Proxy validator functionality for now and keep it simple.  Just put the validation and parameter processing in the same "uploadFiles" function.

2017-05-08 16:02 UTC, DerekSeverson commented on lib/service.js
> +      const stream = fs.createReadStream(file);
@tttmaximttt - we would rather accept an array of "Buffers" and "ReadStreams".   We should not be creating the readstream from a file path ourselves.  The Developer (SDK user) should create his/her own buffers/readstreams from files (or anything else for that matter), and then pass that to us.  Add validation to ensure we only are excepting an arrays that have Buffers and ReadStreams.  
<img width="1155" alt="class__aws_s3_ _aws_sdk_for_javascript" src="https://cloud.githubusercontent.com/assets/3407325/25812926/7f4cfd28-33dd-11e7-9c86-4fa494b257b6.png">

2017-05-08 16:02 UTC, DerekSeverson commented on lib/validators/service.validator.js
> +const {
@tttmaximttt - delete.  Just add validation to the method itself.

2017-05-10 09:49 UTC, tttmaximttt commented on .gitignore
> +.idea/workspace.xml
fix

2017-05-10 09:49 UTC, tttmaximttt commented on lib/service.js
> +    return proxy;
fix

2017-05-10 09:49 UTC, tttmaximttt commented on lib/service.js
> +      const stream = fs.createReadStream(file);
fix

2017-05-10 09:50 UTC, tttmaximttt commented on lib/validators/service.validator.js
> +const {
fix

2017-05-10 14:42 UTC, DerekSeverson requested changes
a few more changes needed.

2017-05-10 14:42 UTC, DerekSeverson commented on test/service.js
> +        bufFile:  new Buffer('asfasfas'),
Using the Buffer constructor is frowned upon and is deprecated:  https://nodejs.org/api/buffer.html#buffer_new_buffer_string_encoding
Use `Buffer.from(string)` method instead.
https://nodejs.org/api/buffer.html#buffer_class_method_buffer_from_string_encoding

2017-05-10 14:42 UTC, DerekSeverson commented on lib/util.js
> +const { Readable,  Duplex, Transform } = require('stream');
eslint should have shown errors for "unused variables".

2017-05-10 14:42 UTC, DerekSeverson commented on lib/service.js
> +  static _checFormData(formData) {
Extra function not needed, just add validation into `upload` method itself. 
Keep the interface of the `Service` class as clean/minimal as possible without extra methods - even if its an underscore/private method.

2017-05-10 14:42 UTC, DerekSeverson commented on lib/service.js
> +  }
Iterate through the formData's values and validation each of them to make sure they have proper values as well.

2017-05-10 14:42 UTC, DerekSeverson commented on lib/service.js
> +   * [Request formData]{@link https://github.com/request/request#forms}
cool!

2017-05-10 14:42 UTC, DerekSeverson commented on lib/service.js
> +} = require('lodash');
wait ... we don't have `lodash` as a dependency.  I don't believe these can be used here.  For now, I think we're wanting to get by without using lodash ... trying to keep dependencies to a minimum.  We may need to later, but not for now.

2017-05-10 14:51 UTC, tttmaximttt commented on lib/service.js
> +  }
But what a proper values for formData, in formData we can have any types o fields, what exactly I should check?

2017-05-10 14:52 UTC, tttmaximttt commented on lib/service.js
> +  }
And a part of validation realized in request lib.

2017-05-10 15:10 UTC, DerekSeverson commented on lib/service.js
> +  }
Sounds good.  I agree.

2017-05-12 12:25 UTC, DerekSeverson approved these changes
Looks good.

2017-05-12 12:35 UTC, merged